<?php
/**
 * Created by PhpStorm.
 * User: Angoo
 * Date: 2017/5/17
 * Time: 16:12
 * 需要验证登录获取数据的基础类
 */

namespace api\controllers;

use api\models\Organization;
use api\models\SystemUser;
use api\models\User;
use yii\web\Response;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;
use yii\filters\Cors;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;
use Yii;
use yii\web\BadRequestHttpException;

class BaseAPIAuthController extends BaseController
{
    public $post = null;
    public $get = null;
    public $user = null;
    public $userId = null;
    public $schoolId = null;
    public $schoolName = null;

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        //$behaviors['authenticator']['class'] = QueryParamAuth::className();
        return $behaviors;
    }

/*  public function beforeAction($action)
   {
        //验证用户权限
        $this->checkPermission();

        //验证所属学校和端
       parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->post = yii::$app->request->post();
        $this->get = yii::$app->request->get();
        $this->user = yii::$app->user->identity;
        $this->userId = Yii::$app->user->id;

        //获取学校id
      $schoolId = Organization::getOrganizationId();
        if(isset($schoolId)){
            $this->schoolId = $schoolId;
        }else{
            throw new BadRequestHttpException('非法路径');
        }

        return $action;
   }*/

    public function checkPermission()
    {
        $actionName = \Yii::$app->controller->action->id;
        $controllerName = \Yii::$app->controller->id;
        $url = $controllerName.'/'.$actionName;
        var_dump($url);exit;
        $user = SystemUser::findByUsername('admin');
        \Yii::$app->user->login($user,true);
        var_dump(\Yii::$app->user->id);exit;
        if(\Yii::$app->user->can($action)){
            return true;
        }else{
            throw new \yii\web\UnauthorizedHttpException('对不起，您现在还没获此操作的权限');
        }
    }


}